name: Automated API tests using Postman CLI

on: 
  workflow_dispatch:  
  push:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "30057603-78b4f517-8af1-43a5-be28-210e1f1ccc04"

      - name: postman logout
        run: ${{ secrets.POSTMAN_API_KEY }}
